exam/urls.py
from django.conf.urls import url
from exam import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^chapter/(\d+)/$',views.chapter,name='chapter'),
    url(r'^chapter/do/(\d+)/$', views.chapter_do, name='chapter_do'),
    url(r'^chapter/addpractice$',views.add_practices,name='add_practice'),
    url(r'^selfdo/save_result$',views.save_result,name='show_result'),
    url(r'^selfdo/show_record/(\d+)$',views.show_record,name='show_record'),
    url(r'^error$',views.error,name='error'),
    url(r'^error/type$',views.select_error_type,name='error_type'),
    url(r'error/show$',views.show_error,name='show_error'),
    url(r'^practice$',views.practice,name='record'),
    url(r'^practice/(\d+)/(\d+)$',views.practice2,name='record2'),
    url(r'^exam$',views.exam,name='exam'),
]

onlineExam/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^exam/',include('exam.urls',namespace='exam'))
]

exam/models.py
from django.db import models
from datetime import datetime

from user.models import StudentInfo,TeacherInfo


# 章节表
class ChapterItems(models.Model):
    '''
    作用：学科章节表
    ctitle:标题
    subject：属于哪个学科
    '''
    ctitle = models.CharField(max_length=30)
    subject = models.ForeignKey('self',null=True)


    def get_cover(self):
        path = 'images/exam/cover/%d.jpg'%self.pk
        return path

    def __str__(self):
        return self.ctitle


# 题库
class Questions(models.Model):

    chapter = models.ForeignKey(ChapterItems, null=True)
    que_type = models.CharField(max_length=10) # 题目类型：1:select,2:judge,3:subject
    que_content = models.CharField(max_length=500)  # 题目内容
    que_A = models.CharField(max_length=30,null=True) # 选择题
    que_B = models.CharField(max_length=30,null=True)
    que_C = models.CharField(max_length=30,null=True)
    que_D = models.CharField(max_length=30,null=True)
    que_answer = models.CharField(max_length=600) # 答案
    level = models.CharField(max_length=1)   # 难度：1,2,3
    point_value = models.IntegerField(default=0)  # 分值：默认0

    def __str__(self):
        return str(self.pk)

    def switch_answer(self):
        if self.que_answer == '1':
            return '✔'
        else:
            return '✘'

# 选择题题库
# class SelectQuestions(models.Model):
#
#     chapter = models.ForeignKey(ChapterItems,null=True)
#     que_content = models.CharField(max_length=50)
#     que_A = models.CharField(max_length=30)
#     que_B = models.CharField(max_length=30)
#     que_C = models.CharField(max_length=30)
#     que_D = models.CharField(max_length=30)
#     answer = models.CharField(max_length=1)  # 答案：A B C D
#     level = models.CharField(max_length=1)   # 难度：0 1 2
#     point_value = models.IntegerField(default=1) # 分值：默认1

# 判断题题库
# class JudgeQuestions(models.Model):
#
#     chapter = models.ForeignKey(ChapterItems, null=True)
#     que_content = models.CharField(max_length=50)
#     answer = models.CharField(max_length=1) # 答案：0：错误，1：正确
#     level = models.CharField(max_length=1)
#     point_value = models.IntegerField(default=1)


# 主观题题库
# class SubjectiveQuestions(models.Model):
#
#     chapter = models.ForeignKey(ChapterItems, null=True)
#     que_content = models.CharField(max_length=150)
#     answer = models.CharField(max_length=300)
#     level = models.CharField(max_length=1)
#     point_value = models.IntegerField(default=20)

'''考试信息表'''
class ExamInfo(models.Model):

    title = models.CharField(max_length=20) # 考试标题
    exam_time = models.DateTimeField()  # 考试时间
    total_time = models.CharField(max_length=10)   # 考试用时：4：20(这种格式)
    stu = models.ManyToManyField(StudentInfo)
    tea = models.ForeignKey(TeacherInfo)
    mark = models.IntegerField()

    def __str__(self):
        return self.title


# 试卷表
class PaperInfo(models.Model):

    que = models.ForeignKey(Questions)
    exam = models.ForeignKey(ExamInfo)


# 答题记录
class AnswerRecords(models.Model):
    stu = models.ForeignKey(StudentInfo)
    chapter = models.ForeignKey(ChapterItems,null=True)
    exam = models.ForeignKey(ExamInfo,null=True,default=None)
    answer_date = models.DateField(auto_now=True)
    used_time = models.CharField(max_length=10,default='0')

    def switch_used(self):
        slist = self.used_time.split(':')
        if not slist[0] == '0':
            slist[0] = slist[0] + '小时'
        if not slist[1] == '0':
            slist[1] = slist[1] + '分钟'
        if not slist[2] == '0':
            slist[2] = slist[2] + '秒'
        slist = [item for item in slist if not item == '0']
        return ''.join(slist)

    def switch_date(self):
        return datetime.strftime(self.answer_date, '%Y年%m月%d日')

    # 获取总分
    def sum_score(self):
        sums = 0
        for item in self.answer_set.all():
            sum += item.score
        return sums

    #已经做过的题
    def done(self):
        ls = set()
        for item in self.answer_set.all():
            ls.add(item)
            # ls.add(item.pk)
        return ls

    # 没有做过的题
    def notdone(self):
        pass

    # 获取错误题
    def errors(self):
        return self.answer_set.filter(score=0)

    # 获取错误题数
    def errors_count(self):
        err = self.answer_set.filter(score=0)
        return err.count()

    # 获取正确题数
    def success_count(self):
        success = self.answer_set.filter(score__gt=0)
        return success.count()


# 答题表
class Answer(models.Model):

    stu = models.ForeignKey(StudentInfo)
    stu_answer = models.CharField(max_length=300)
    # correct = models.BooleanField()  # 是否正确
    score = models.IntegerField()  # 分数：错误：0,正确：1,主观题：0-20
    answer_record = models.ForeignKey(AnswerRecords)
    que = models.ForeignKey(Questions)

    def switch_answer(self):
        if self.stu_answer == '1':
            return '✔'
        else:
            return '✘'


'''
    获取试卷：
        exam = ExamInfo.objects.get(pk='exam_id')
        exam.paperinfo_set.all()
    获取试卷答题记录：
        exam.answerrecords_set.filter(exam__isnull=False)
    获取某个学生的答题记录：
        records = AnswerRecords.objects.filter(stu_id='').order_by('-answer_date')
        # 所以题
        for record in records:
            record.answer_set.all()
    获取错题：
        for record in records:
            record.answer_set.filter(score=0)                  

'''

exam/views.py
from datetime import datetime
from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse
import json



from exam import models
from exam import handles



# 首页
def index(request):
    request.session['userid'] = '1'
    subjects = models.ChapterItems.objects.filter(subject=None)
    return render(request,'exam/exam_index.html',{'subjects':subjects})

# 章节练习
def chapter(request,subject_id):
    subject = models.ChapterItems.objects.filter(pk=subject_id)
    if subject.exists():
        chapters = subject[0].chapteritems_set.all()
        context = {
            'subject':subject[0],
            'chapters':chapters
        }
        request.session['subject_id'] = subject_id
        return render(request,'exam/chapter.html',context)
    else:
        return redirect(reverse('exam:index'))

# 选择做题模式
def chapter_do(request,chapter_id):
    chapter_obj = models.ChapterItems.objects.filter(pk=chapter_id)
    if chapter_obj.count()==1:
        ques = models.Questions.objects.filter(chapter_id=chapter_id)
        # 章节
        chapter_obj = chapter_obj[0]

        # 试题类型
        que_types = ques.values('que_type').distinct()
        que_types = [item['que_type'] for item in que_types]
        que_types.sort()
        list_type = [(que,handles.get_type(que)) for que in que_types]
        # print(list_type)
        # 试题难度
        que_level = ques.values('level').distinct()
        que_level = [item['level'] for item in que_level]
        que_level.sort()
        list_level = [(que,handles.get_level(que)) for que in que_level]
        # print(list_type)
        # 试题数量
        # count = ques.count()
        stu_id = request.session.get('userid')
        student = models.StudentInfo.objects.get(pk=int(stu_id))
        # 做过题目
        ques = student.answer_set.filter(que__chapter_id=chapter_id).values('que').distinct()
        # 做过的数量
        done = ques.count()
        # 错误的数量
        err = ques.filter(score=0).count()
        sum_ques = models.Questions.objects.filter(chapter_id=chapter_id).count()
        # 没有做的数量
        notdone = sum_ques - done

        context = {
            'chapter':chapter_obj,
            'que_type':list_type,
            'done':done,
            'err':err,
            'notdone':notdone,
            'que_level':list_level,
        }
        return render(request,'exam/select.html',context)
    else:
        return redirect(reverse('exam:index'))

# 自测
def add_practices(request):
    chapter_id = request.GET.get('chapter_id') # 章节
    model = request.GET.get('filter')  # 做题模式：0 未做 1 已做 2 错误
    degree =request.GET.get('degree')  # 难度 0:全部
    quantity = request.GET.get('quantity') # 数量
    title = request.GET.get('title') #
    typeid = request.GET.get('typeid') # 题目类型
    if model == '0':
        ques = handles.notdone_ques(request,chapter_id)
    elif models == '1':
        ques = handles.done_ques(request,chapter_id)
    else:
        ques = handles.err_ques(request,chapter_id)
    if not degree == '0':
        ques = ques.filter(level=degree)
    ques = ques.filter(que_type=typeid).order_by('?')[:int(quantity)]
    # ques = serializers.serialize('json',ques)
    context = {
        'title':title,
        'chapter':chapter_id,
        'type':handles.get_type(typeid),
        'ques':ques,
        'count':ques.count(),
        'ques_list':','.join([str(item.pk) for item in ques]),
        'answer_list':[a for a in range(ques.count())]
    }
    return render(request,'exam/selfdo.html',context)

# 保存做题记录
def save_result(request):
    chapter_id = request.POST.get('chapter')
    ques_ids = request.POST.get('ques_ids')
    used_time = request.POST.get('used_time')
    student = handles.get_student(request)
    answer_record = models.AnswerRecords(stu=student,chapter_id=int(chapter_id),exam=None,used_time=used_time)
    answer_record.save()

    ques_ids = ques_ids.split(',')
    err = 0
    for item in ques_ids:
        answer = request.POST.get(item)
        que = models.Questions.objects.get(pk=item)
        if answer == que.que_answer:
            score = 1
        else:
            score = 0
            err += 1
        ans = models.Answer(stu=student,stu_answer=answer,score=score,answer_record=answer_record,que=que)
        ans.save()

    s = '总共%d题，正确：%d，错误：%d'%(len(ques_ids),len(ques_ids)-err,err)
    print(s)
    return redirect(reverse('exam:show_record',args=(answer_record.pk,)))

# 显示做题结果
def show_record(request,record_id):
    stu_id = request.session.get('userid')
    record = models.AnswerRecords.objects.filter(pk=record_id,stu_id=int(stu_id))
    if record.exists():
        record = record[0]
        answer = record.answer_set.first()
        context = {
            'title':record.chapter.ctitle,
            'count':record.answer_set.count(),
            'err':record.errors_count(),
            'success':record.success_count(),
            'used_time':record.switch_used(),
            'answers': record.answer_set.all(),
            'type':handles.get_type(answer.que.que_type),
            'answer_date':datetime.strftime(record.answer_date,'%Y年%m月%d日')
        }
        return render(request,'exam/showrecord.html',context)
    else:
        return HttpResponse('没有查询到该记录！')

# 选择错题类型
@csrf_exempt
def select_error_type(request):
    error_type = request.POST.get('type','0')
    stu_id = request.session.get('userid')
    records = models.AnswerRecords.objects.filter(stu_id=int(stu_id),answer__score=0).distinct()
    if not error_type == '0':
        records = records.filter(answer__que__que_type=error_type)
    context = records.values('chapter').distinct()
    # 初始化：每个章节
    for item in context:
        item['title'] = models.ChapterItems.objects.get(pk=item['chapter'])
        item['sumcount'] = models.Questions.objects.filter(chapter_id=item['chapter']).count()
        item['errcount'] = 0
        item['errs'] = set()
    # 获取每个章节的错题
    for record in records:
        for item in context:
            if item['chapter'] == record.chapter_id:
                ids = [item['que_id'] for item in record.answer_set.values('que_id')]
                item['errs'].update(ids)

    # 设置每个章节错题数
    for item in context:
        item['errcount'] = len(item['errs'])
        # item['errs'] = ','.join(str(item) for item in t[0]['errs'])
    print(context)
    # records = records.order_by('chapter_id')
    return render(request,'exam/module/error_select_type.html',{'context':context,'count':len(context)})

# 查看错题
def show_error(request):
    errs = request.GET.get('errs').replace('{','[').replace('}',']')
    title = request.GET.get('title')
    errs = json.loads(errs)
    questions = models.Questions.objects.filter(pk__in = errs)

    return render(request,'exam/showerrors.html',{'questions':questions,'title':title})

# 错题集锦
def error(request):
    return render(request,'exam/errorquestion.html')

# 练习记录
def practice2(request,model,que_type):
    stu_id = request.session.get('userid')
    record = models.AnswerRecords.objects.filter(stu_id=int(stu_id))

    # 章节
    if model == '0':
        record = record.filter(exam=None)
        if not que_type == '0':
            record = record.filter(answer__que__que_type=que_type).distinct()
    # 考试
    else:
        record = record.exclude(exam=None)
    record = record.order_by('-pk')
    return render(request,'exam/record.html',{'records':record,'model':model,'que_type':que_type})

# 练习记录
def practice(request):
    return practice2(request,'0','0')


# 我的考试
def exam(request):
    return render(request,'exam/exam.html')


'''
使用Django从数据库中随机取N条记录的不同方法
1.使用mysql数据库，数据量在百万级以下时
    Record.objects.order_by('?')[:2]
2.数据量在百万级以上时
    sample = random.sample(xrange(Record.objects.count()),n)  
    result = [Record.objects.all()[i]) for i in sample]
'''

templates/exam/base_exam.html
{% extends 'exam/base.html' %}
{% load static from staticfiles %}
{% block tiku %}class="li_on"{% endblock %}
{% block body %}
<div class="main_bg p_t">
    <div class="chapterbg">
        <div class="chapter_main">
            <div class="chapter_menu">
                <div class="chapter_nav">
                    <a nav-for="chapter" href="{% url 'exam:chapter' request.session.subject_id %}" target="_top" title="章节考点" {% block chapter %}{% endblock %}>章节考点</a>
                    <a nav-for="paper" href="{% url 'exam:chapter' request.session.subject_id %}" target="_top" title="试卷练习" {% block pater %}{% endblock %}>试卷练习</a>
                    <a nav-for="error" href="{% url 'exam:error' %}" target="_top" title="错题集锦" {% block error %}{% endblock %}>错题集锦</a>
                    <a nav-for="record" href="{% url 'exam:record' %}" target="_top" title="练习记录" {% block record %}{% endblock %}>练习记录</a>
                    <a nav-for="exam" href="{% url 'exam:exam'%}" target="_top" title="我的考试" {% block exam %}{% endblock %}>我的考试</a>

                </div>
                <div class="chapter1_fr">
                    <div class="date">
                        <p class="font_1">距离<span class="f60" title="理论知识">理论知识</span>考试</p>
                        <p class="font_2">还有<span class="sp_2 sp_bg1">0</span>天</p>
                    </div>
                </div>
                <div class="back">
                    <a class="qia" href="http://tiku.kaola100.com/tiku/" target="_top">在线考试</a>
                </div>
            </div>
            <div class="chapter_content">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/exam/chapter.html
{% extends 'exam/base_exam.html' %}
{% load static from staticfiles %}
{% block title %}章节考点{% endblock %}
{% block chapter %}class="aon"{% endblock %}
{% block content %}
    <div class="chapter_1">
        <div class="chapter1_fl">
            <div class="position">
                <span class="sp_1">章节总数{{ chapters.count }}</span>|<span class="sp_1">学习人数20162</span>
            </div>
            <div class="fl_img f_l">
                <img src="{% static subject.get_cover %}" alt="{{ subject.ctitle }}">
            </div>
            <div class="fl_detil f_l">
                <h2 class="h2tit">
                    {{ subject.ctitle }}
                </h2>
                <p class="price">价格：<em>¥0.00</em>元</p>
                <p class="intro">描述：{{ subject.ctitle }}</p>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div class="chapter_2">
        <div class="kemu">
            <span class="s_bold f_l">选择章节：</span>
            <div class="clear"></div>
        </div>
        <h2 class="z_icon">章节考点</h2>
        <!--章节考点 开始标记-->
        <div id="treelist" style="padding-bottom:60px;">
            {% for chapter in chapters %}
                <div data-parentid="0" data-id="" style="" class="zj_list d_p1">
                    <div class="z_cont f_l">
                        <p class="p_a1">
                            <a href="javascript:void(0)">
                                <i data-parentid="0" data-id="" class="f_l">&nbsp;</i>{{ chapter.ctitle }}
                            </a>
                            <span>（总共{{ chapter.questions_set.count }}题）</span>
                        </p>
                    </div>
                    <div class="f_r lbtn">
                        <a href="{% url 'exam:chapter_do' chapter.pk%}" {% if chapter.questions_set.count == 0 %} onclick="window.alert('当前章节还没有练习题！'); return false;" {% endif %}>开始做题</a>
                    </div>
                    <div class="clear"></div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

templates/exam/errorquestion.html
{% extends 'exam/base_exam.html' %}
{% load static from staticfiles %}
{% block title %}我的错题{% endblock %}
{% block error %}class="aon"{% endblock %}
{% block content %}
    <div class="error_fr">
        <div class="error_c1">
            <h2 class="h2_err">我的错题</h2>
            <div class="kemu">
                <div class="ke_sort">
                    <span class="s_bold f_l">题目类型：</span>
                    <div class="alist f_l">
                        <a href="javascript:void(null)" title="全部">全部</a>
                        <a data="type=1" href="javascript:void(null)" title="选择题">选择题</a>
                        <a data="type=2" href="javascript:void(null)" title="判断题">判断题</a>
                        <a data="type=3" href="javascript:void(null)" title="主观题">主观题</a>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="error_c2">
            <div class="errd_div">
                <h3 class="h3_err">按章节归类</h3>
            </div>
            <div class="chapter-tree" style="padding-bottom:60px;">
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <script type="text/javascript" src="{% static 'js/public/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        $('.alist a').on('click',function () {
            $(this).addClass('am_on').siblings().removeClass('am_on');
            $.ajax({
                url:"{% url 'exam:error_type' %}",
                type:'POST',
                data:$(this).attr('data'),
                success:function (data) {
                    $('.chapter-tree').html(data)
                }
            })
        });
        $('.alist a:first').click();
    </script>
{% endblock %}

templates/exam/exam_index.html
{% extends 'exam/base.html' %}
{% load static from staticfiles %}
{% block title %}题库{% endblock %}
{% block index %}class="li_on"{% endblock %}
{% block body %}
    <div class="layout">
        <div class="m_w">
            <img src="{% static 'images/exam/banner1.jpg' %}" border="0" alt="" usemap="#Map" id="img_pick">
        </div>
    </div>
    <div class="main_bg">
        <div class="main">
            <h2 class="tk_title" id="select">选择学科</h2>
            <div class="m_content">
                {% for subject in subjects %}
                    <dl class="sort_dl">
                        <dt class="dt_img"><a href="{% url 'exam:chapter' subject.pk %}" title="{{ subject.ctitle }}">
                            <img alt="{{ subject.ctitle }}" title="{{ subject.ctitle }}" src="{% static 'images/exam/20150720170910697.png' %}"></a>
                        </dt>
                        <dd class="dd_tit"><a href="{% url 'exam:chapter' subject.pk %}" title="{{ subject.ctitle }}">{{ subject.ctitle }}</a></dd>
                        <dd class="dd_detil">
                            <p></p>
                        </dd>
                    </dl>
                {% endfor %}
                <dl class="sort_dl">
                    <dt class="dt_img"><a href="http://tiku.kaola100.com/tiku/3" target="_blank" title="医药卫生"><img alt="医药卫生" title="医药卫生" src="{% static 'images/exam/20150714113357871.png' %}"></a></dt>
                    <dd class="dd_tit"><a href="http://tiku.kaola100.com/tiku/3" target="_blank" title="医药卫生">医药卫生</a></dd>
                    <dd class="dd_detil">
                        <p></p>
                    </dd>
                </dl>
                <dl class="sort_dl">
                    <dt class="dt_img"><a href="http://tiku.kaola100.com/tiku/4" target="_blank" title="职业资格"><img alt="职业资格" title="职业资格" src="{% static 'images/exam/20150521184649758.png' %}"></a></dt>
                    <dd class="dd_tit"><a href="http://tiku.kaola100.com/tiku/4" target="_blank" title="职业资格">职业资格</a></dd>
                    <dd class="dd_detil">
                        <p></p>
                    </dd>
                </dl>
                <dl class="sort_dl">
                    <dt class="dt_img"><a href="http://tiku.kaola100.com/tiku/6" target="_blank" title="外语"><img alt="外语" title="外语" src="{% static 'images/exam/20150521184732112.png' %}"></a></dt>
                    <dd class="dd_tit"><a href="http://tiku.kaola100.com/tiku/6" target="_blank" title="外语">外语</a></dd>
                    <dd class="dd_detil">
                        <p></p>
                    </dd>
                </dl>
                <dl class="sort_dl">
                    <dt class="dt_img"><a href="http://tiku.kaola100.com/tiku/7" target="_blank" title="公务员"><img alt="公务员" title="公务员" src="{% static 'images/exam/20150521184614045.png' %}"></a></dt>
                    <dd class="dd_tit"><a href="http://tiku.kaola100.com/tiku/7" target="_blank" title="公务员">公务员</a></dd>
                    <dd class="dd_detil">
                        <p></p>
                    </dd>
                </dl>
                <dl class="sort_dl">
                    <dt class="dt_img"><a href="http://tiku.kaola100.com/tiku/1" target="_blank" title="自考类"><img alt="自考类" title="自考类" src="{% static 'images/exam/20150521183838915.png' %}"></a></dt>
                    <dd class="dd_tit"><a href="http://tiku.kaola100.com/tiku/1" target="_blank" title="自考类">自考类</a></dd>
                    <dd class="dd_detil">
                        <p></p>
                    </dd>
                </dl>
                <dl class="sort_dl">
                    <dt class="dt_img"><a href="http://tiku.kaola100.com/tiku/12" target="_blank" title="成人高考"><img alt="成人高考" title="成人高考" src="{% static 'images/exam/000010101.png' %}"></a></dt>
                    <dd class="dd_tit"><a href="http://tiku.kaola100.com/tiku/12" target="_blank" title="成人高考">成人高考</a></dd>
                    <dd class="dd_detil">
                        <p></p>
                    </dd>
                </dl>
                <dl class="sort_dl">
                    <dt class="dt_img"><a href="http://tiku.kaola100.com/tiku/" target="_blank"><img alt="更多考试" src="./index_files/more.png"></a></dt>
                    <dd class="dd_tit"><a href="http://tiku.kaola100.com/tiku/" target="_blank">更多</a></dd>
                    <dd class="dd_detil">
                        <p>学历教育领域培训首选品牌组卷模考、押题试卷、真题解析</p>
                    </dd>
                </dl>
                <div class="clear"></div>
            </div>
        </div>
    </div>
{% endblock %}

templates/exam/selfdo.html
<!DOCTYPE HTML>
{% load static from staticfiles %}
<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ title }}</title>
    <link href="{% static 'css/exam/do/main.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/exam/do/iconfont.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/exam/do/test.css' %}" rel="stylesheet" type="text/css" />
    <style>
        .hasBeenAnswer {
            background: #5d9cec;
            color:#fff;
        }
        .err{
            text-align: center;
            margin-top: 30px;
            line-height: 40px;
            font-size: 18px;
        }
        .err p{
            color: red;
        }
        .err a{
            text-decoration: underline;
            color: black;
        }
    </style>
</head>
<body>
{% if count == 0 %}
    <div class="err">
        <p>选择的练习模式没有习题,请重新选择!</p>
        <a href="{% url 'exam:chapter_do' chapter %}" >返回上一级</a>
    </div>
{% else %}
    <div class="main">
        <!--nr start-->
        <div class="test_main">
            <div class="nr_left">
                <div class="test">
                    <form action="{% url 'exam:show_result' %}" method="post">
                        {% csrf_token %}
                        <div class="test_title">
                            <p class="test_time">
                                <i class="icon iconfont">&#xe6fb;</i><span>已用时:</span><b class="alt-1">0:0:0</b>
                            </p>
                            <input type="submit" name="test_jiaojuan" value="交卷" id="submit">
                        </div>
                        <div class="test_content">
                            <div class="test_content_title">
                                <input type="text" value="{{ chapter }}" hidden name="chapter">
                                <input type="text" value="{{ ques_list }}" hidden name="ques_ids">
                                <input type="text" value="" hidden name="used_time" id="used_time">
                                <h2 chapter="{{ chapter }}">{{ title }}</h2>
                                <p>
                                    {{ type }}
                                    {#                                <span>共</span><i class="content_lit">{{ count }}</i><span>题，</span>#}
                                    {#                                <span>合计</span><i class="content_fs">60</i><span>分</span>#}
                                </p>
                            </div>
                        </div>
                        <div class="test_content_nr">
                            <ul>
                                {% include 'exam/question_type.html' %}
                            </ul>
                        </div>
                    </form>
                </div>
            </div>
            <div class="nr_right">
                <div class="nr_rt_main">
                    <div class="rt_nr1">
                        <div class="rt_nr1_title">
                            <h1>
                                <i class="icon iconfont">&#xe692;</i>答题卡
                            </h1>
                            <p class="test_time">
                                <i class="icon iconfont">&#xe6fb;</i><span>已用时:</span><b class="alt-1" id="page-timer-text">0:0:0</b>
                            </p>
                        </div>
                        <div class="rt_content">
                            <div class="rt_content_tt">
                                <h2>{{ type }}</h2>
                                <p>
                                    <span>共</span><i class="content_lit">{{ count }}</i><span>题</span>
                                </p>
                            </div>
                            <div class="rt_content_nr answerSheet">
                                <ul>
                                    {% for item in answer_list %}
                                        <li><a href="#qu_0_{{ forloop.counter }}">{{ forloop.counter }}</a></li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--nr end-->
        <div class="foot"></div>
    </div>
    <script src="{% static 'js/public/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'js/exam/do.js' %}"></script>
{% endif %}

</body>
</html>







