exam/urls.py
from django.conf.urls import url
from exam import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^chapter/(\d+)/$',views.chapter,name='chapter'),
    url(r'^chapter/do/(\d+)/$', views.chapter_do, name='chapter_do'),
    url(r'^chapter/addpractice$',views.add_practices,name='add_practice'),
    url(r'^selfdo/save_result$',views.save_result,name='show_result'),
    url(r'^selfdo/show_record/(\d+)$',views.show_record,name='show_record'),
    url(r'^error$',views.error,name='error'),
    url(r'^error/type$',views.select_error_type,name='error_type'),
    url(r'error/show$',views.show_error,name='show_error'),
    url(r'^practice$',views.practice,name='record'),
    url(r'^practice/(\d+)/(\d+)$',views.practice2,name='record2'),
    url(r'^exam$',views.exam,name='exam'),
]

onlineExam/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^exam/',include('exam.urls',namespace='exam'))
]

exam/models.py
from django.db import models
from datetime import datetime

from user.models import StudentInfo,TeacherInfo


# 章节表
class ChapterItems(models.Model):
    '''
    作用：学科章节表
    ctitle:标题
    subject：属于哪个学科
    '''
    ctitle = models.CharField(max_length=30)
    subject = models.ForeignKey('self',null=True)


    def get_cover(self):
        path = 'images/exam/cover/%d.jpg'%self.pk
        return path

    def __str__(self):
        return self.ctitle


# 题库
class Questions(models.Model):

    chapter = models.ForeignKey(ChapterItems, null=True)
    que_type = models.CharField(max_length=10) # 题目类型：1:select,2:judge,3:subject
    que_content = models.CharField(max_length=500)  # 题目内容
    que_A = models.CharField(max_length=30,null=True) # 选择题
    que_B = models.CharField(max_length=30,null=True)
    que_C = models.CharField(max_length=30,null=True)
    que_D = models.CharField(max_length=30,null=True)
    que_answer = models.CharField(max_length=600) # 答案
    level = models.CharField(max_length=1)   # 难度：1,2,3
    point_value = models.IntegerField(default=0)  # 分值：默认0

    def __str__(self):
        return str(self.pk)

    def switch_answer(self):
        if self.que_answer == '1':
            return '✔'
        else:
            return '✘'

# 选择题题库
# class SelectQuestions(models.Model):
#
#     chapter = models.ForeignKey(ChapterItems,null=True)
#     que_content = models.CharField(max_length=50)
#     que_A = models.CharField(max_length=30)
#     que_B = models.CharField(max_length=30)
#     que_C = models.CharField(max_length=30)
#     que_D = models.CharField(max_length=30)
#     answer = models.CharField(max_length=1)  # 答案：A B C D
#     level = models.CharField(max_length=1)   # 难度：0 1 2
#     point_value = models.IntegerField(default=1) # 分值：默认1

# 判断题题库
# class JudgeQuestions(models.Model):
#
#     chapter = models.ForeignKey(ChapterItems, null=True)
#     que_content = models.CharField(max_length=50)
#     answer = models.CharField(max_length=1) # 答案：0：错误，1：正确
#     level = models.CharField(max_length=1)
#     point_value = models.IntegerField(default=1)


# 主观题题库
# class SubjectiveQuestions(models.Model):
#
#     chapter = models.ForeignKey(ChapterItems, null=True)
#     que_content = models.CharField(max_length=150)
#     answer = models.CharField(max_length=300)
#     level = models.CharField(max_length=1)
#     point_value = models.IntegerField(default=20)

'''考试信息表'''
class ExamInfo(models.Model):

    title = models.CharField(max_length=20) # 考试标题
    exam_time = models.DateTimeField()  # 考试时间
    total_time = models.CharField(max_length=10)   # 考试用时：4：20(这种格式)
    stu = models.ManyToManyField(StudentInfo)
    tea = models.ForeignKey(TeacherInfo)
    mark = models.IntegerField()

    def __str__(self):
        return self.title


# 试卷表
class PaperInfo(models.Model):

    que = models.ForeignKey(Questions)
    exam = models.ForeignKey(ExamInfo)


# 答题记录
class AnswerRecords(models.Model):
    stu = models.ForeignKey(StudentInfo)
    chapter = models.ForeignKey(ChapterItems,null=True)
    exam = models.ForeignKey(ExamInfo,null=True,default=None)
    answer_date = models.DateField(auto_now=True)
    used_time = models.CharField(max_length=10,default='0')

    def switch_used(self):
        slist = self.used_time.split(':')
        if not slist[0] == '0':
            slist[0] = slist[0] + '小时'
        if not slist[1] == '0':
            slist[1] = slist[1] + '分钟'
        if not slist[2] == '0':
            slist[2] = slist[2] + '秒'
        slist = [item for item in slist if not item == '0']
        return ''.join(slist)

    def switch_date(self):
        return datetime.strftime(self.answer_date, '%Y年%m月%d日')

    # 获取总分
    def sum_score(self):
        sums = 0
        for item in self.answer_set.all():
            sum += item.score
        return sums

    #已经做过的题
    def done(self):
        ls = set()
        for item in self.answer_set.all():
            ls.add(item)
            # ls.add(item.pk)
        return ls

    # 没有做过的题
    def notdone(self):
        pass

    # 获取错误题
    def errors(self):
        return self.answer_set.filter(score=0)

    # 获取错误题数
    def errors_count(self):
        err = self.answer_set.filter(score=0)
        return err.count()

    # 获取正确题数
    def success_count(self):
        success = self.answer_set.filter(score__gt=0)
        return success.count()


# 答题表
class Answer(models.Model):

    stu = models.ForeignKey(StudentInfo)
    stu_answer = models.CharField(max_length=300)
    # correct = models.BooleanField()  # 是否正确
    score = models.IntegerField()  # 分数：错误：0,正确：1,主观题：0-20
    answer_record = models.ForeignKey(AnswerRecords)
    que = models.ForeignKey(Questions)

    def switch_answer(self):
        if self.stu_answer == '1':
            return '✔'
        else:
            return '✘'


'''
    获取试卷：
        exam = ExamInfo.objects.get(pk='exam_id')
        exam.paperinfo_set.all()
    获取试卷答题记录：
        exam.answerrecords_set.filter(exam__isnull=False)
    获取某个学生的答题记录：
        records = AnswerRecords.objects.filter(stu_id='').order_by('-answer_date')
        # 所以题
        for record in records:
            record.answer_set.all()
    获取错题：
        for record in records:
            record.answer_set.filter(score=0)                  

'''

exam/views.py
from datetime import datetime
from django.shortcuts import render,redirect
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse
import json



from exam import models
from exam import handles



# 首页
def index(request):
    request.session['userid'] = '1'
    subjects = models.ChapterItems.objects.filter(subject=None)
    return render(request,'exam/exam_index.html',{'subjects':subjects})

# 章节练习
def chapter(request,subject_id):
    subject = models.ChapterItems.objects.filter(pk=subject_id)
    if subject.exists():
        chapters = subject[0].chapteritems_set.all()
        context = {
            'subject':subject[0],
            'chapters':chapters
        }
        request.session['subject_id'] = subject_id
        return render(request,'exam/chapter.html',context)
    else:
        return redirect(reverse('exam:index'))

# 选择做题模式
def chapter_do(request,chapter_id):
    chapter_obj = models.ChapterItems.objects.filter(pk=chapter_id)
    if chapter_obj.count()==1:
        ques = models.Questions.objects.filter(chapter_id=chapter_id)
        # 章节
        chapter_obj = chapter_obj[0]

        # 试题类型
        que_types = ques.values('que_type').distinct()
        que_types = [item['que_type'] for item in que_types]
        que_types.sort()
        list_type = [(que,handles.get_type(que)) for que in que_types]
        # print(list_type)
        # 试题难度
        que_level = ques.values('level').distinct()
        que_level = [item['level'] for item in que_level]
        que_level.sort()
        list_level = [(que,handles.get_level(que)) for que in que_level]
        # print(list_type)
        # 试题数量
        # count = ques.count()
        stu_id = request.session.get('userid')
        student = models.StudentInfo.objects.get(pk=int(stu_id))
        # 做过题目
        ques = student.answer_set.filter(que__chapter_id=chapter_id).values('que').distinct()
        # 做过的数量
        done = ques.count()
        # 错误的数量
        err = ques.filter(score=0).count()
        sum_ques = models.Questions.objects.filter(chapter_id=chapter_id).count()
        # 没有做的数量
        notdone = sum_ques - done

        context = {
            'chapter':chapter_obj,
            'que_type':list_type,
            'done':done,
            'err':err,
            'notdone':notdone,
            'que_level':list_level,
        }
        return render(request,'exam/select.html',context)
    else:
        return redirect(reverse('exam:index'))

# 自测
def add_practices(request):
    chapter_id = request.GET.get('chapter_id') # 章节
    model = request.GET.get('filter')  # 做题模式：0 未做 1 已做 2 错误
    degree =request.GET.get('degree')  # 难度 0:全部
    quantity = request.GET.get('quantity') # 数量
    title = request.GET.get('title') #
    typeid = request.GET.get('typeid') # 题目类型
    if model == '0':
        ques = handles.notdone_ques(request,chapter_id)
    elif models == '1':
        ques = handles.done_ques(request,chapter_id)
    else:
        ques = handles.err_ques(request,chapter_id)
    if not degree == '0':
        ques = ques.filter(level=degree)
    ques = ques.filter(que_type=typeid).order_by('?')[:int(quantity)]
    # ques = serializers.serialize('json',ques)
    context = {
        'title':title,
        'chapter':chapter_id,
        'type':handles.get_type(typeid),
        'ques':ques,
        'count':ques.count(),
        'ques_list':','.join([str(item.pk) for item in ques]),
        'answer_list':[a for a in range(ques.count())]
    }
    return render(request,'exam/selfdo.html',context)

# 保存做题记录
def save_result(request):
    chapter_id = request.POST.get('chapter')
    ques_ids = request.POST.get('ques_ids')
    used_time = request.POST.get('used_time')
    student = handles.get_student(request)
    answer_record = models.AnswerRecords(stu=student,chapter_id=int(chapter_id),exam=None,used_time=used_time)
    answer_record.save()

    ques_ids = ques_ids.split(',')
    err = 0
    for item in ques_ids:
        answer = request.POST.get(item)
        que = models.Questions.objects.get(pk=item)
        if answer == que.que_answer:
            score = 1
        else:
            score = 0
            err += 1
        ans = models.Answer(stu=student,stu_answer=answer,score=score,answer_record=answer_record,que=que)
        ans.save()

    s = '总共%d题，正确：%d，错误：%d'%(len(ques_ids),len(ques_ids)-err,err)
    print(s)
    return redirect(reverse('exam:show_record',args=(answer_record.pk,)))

# 显示做题结果
def show_record(request,record_id):
    stu_id = request.session.get('userid')
    record = models.AnswerRecords.objects.filter(pk=record_id,stu_id=int(stu_id))
    if record.exists():
        record = record[0]
        answer = record.answer_set.first()
        context = {
            'title':record.chapter.ctitle,
            'count':record.answer_set.count(),
            'err':record.errors_count(),
            'success':record.success_count(),
            'used_time':record.switch_used(),
            'answers': record.answer_set.all(),
            'type':handles.get_type(answer.que.que_type),
            'answer_date':datetime.strftime(record.answer_date,'%Y年%m月%d日')
        }
        return render(request,'exam/showrecord.html',context)
    else:
        return HttpResponse('没有查询到该记录！')

# 选择错题类型
@csrf_exempt
def select_error_type(request):
    error_type = request.POST.get('type','0')
    stu_id = request.session.get('userid')
    records = models.AnswerRecords.objects.filter(stu_id=int(stu_id),answer__score=0).distinct()
    if not error_type == '0':
        records = records.filter(answer__que__que_type=error_type)
    context = records.values('chapter').distinct()
    # 初始化：每个章节
    for item in context:
        item['title'] = models.ChapterItems.objects.get(pk=item['chapter'])
        item['sumcount'] = models.Questions.objects.filter(chapter_id=item['chapter']).count()
        item['errcount'] = 0
        item['errs'] = set()
    # 获取每个章节的错题
    for record in records:
        for item in context:
            if item['chapter'] == record.chapter_id:
                ids = [item['que_id'] for item in record.answer_set.values('que_id')]
                item['errs'].update(ids)

    # 设置每个章节错题数
    for item in context:
        item['errcount'] = len(item['errs'])
        # item['errs'] = ','.join(str(item) for item in t[0]['errs'])
    print(context)
    # records = records.order_by('chapter_id')
    return render(request,'exam/module/error_select_type.html',{'context':context,'count':len(context)})

# 查看错题
def show_error(request):
    errs = request.GET.get('errs').replace('{','[').replace('}',']')
    title = request.GET.get('title')
    errs = json.loads(errs)
    questions = models.Questions.objects.filter(pk__in = errs)

    return render(request,'exam/showerrors.html',{'questions':questions,'title':title})

# 错题集锦
def error(request):
    return render(request,'exam/errorquestion.html')

# 练习记录
def practice2(request,model,que_type):
    stu_id = request.session.get('userid')
    record = models.AnswerRecords.objects.filter(stu_id=int(stu_id))

    # 章节
    if model == '0':
        record = record.filter(exam=None)
        if not que_type == '0':
            record = record.filter(answer__que__que_type=que_type).distinct()
    # 考试
    else:
        record = record.exclude(exam=None)
    record = record.order_by('-pk')
    return render(request,'exam/record.html',{'records':record,'model':model,'que_type':que_type})

# 练习记录
def practice(request):
    return practice2(request,'0','0')


# 我的考试
def exam(request):
    return render(request,'exam/exam.html')


'''
使用Django从数据库中随机取N条记录的不同方法
1.使用mysql数据库，数据量在百万级以下时
    Record.objects.order_by('?')[:2]
2.数据量在百万级以上时
    sample = random.sample(xrange(Record.objects.count()),n)  
    result = [Record.objects.all()[i]) for i in sample]
'''

templates/exam/module/error_select_type.html
{% if count == 0 %}
    <div style="display: block;" class="zj_list d_p2">没有查询到相关记录！</div>
{% else %}
    {% for item in context %}
        <div data-parentid="678" data-id="974" style="display: block;" class="zj_list d_p2">
            <div></div>
            <div class="z_cont f_l">
                <p class="p_a1">
                    <a data-parentid="678" data-id="974" href="javascript:void(0)">
                        <i class="f_l zicon_">&nbsp;</i>{{ item.title  }}</a>
                    <span>（总共{{ item.sumcount }}题）</span><span class="icon_1">错题：{{ item.errcount }}</span>
                </p>
            </div>
            <div class="f_r lbtn">
                <a href="{% url 'exam:show_error' %}?errs={{ item.errs }}&title={{ item.title }}">查看</a>&nbsp;&nbsp;
            </div>
            <div class="clear"></div>
        </div>
    {% endfor %}
{% endif %}

templates/exam/module/judgemodel.html
<li class="option">
    <input value="1" type="radio" class="radioOrCheck" name="answer{{ forloop.counter }}" id="0_answer_{{ forloop.counter }}_option_1"/>
    <label for="0_answer_{{ forloop.counter }}_option_1">
        <p class="ue" style="display: inline;">正确</p>
    </label>
</li>
<li class="option">
    <input value="0" type="radio" class="radioOrCheck" name="answer{{ forloop.counter }}" id="0_answer_{{ forloop.counter }}_option_2"/>
    <label for="0_answer_{{ forloop.counter }}_option_2">
        <p class="ue" style="display: inline;">错误</p>
    </label>
</li>

templates/exam/module/selectmodel.html
<li class="option">
    <input value="A" type="radio" class="radioOrCheck" name="answer{{ forloop.counter }}" id="0_answer_{{ forloop.counter }}_option_1"/>
    <label for="0_answer_{{ forloop.counter }}_option_1">
        A.<p class="ue" style="display: inline;">{{ que.que_A }}</p>
    </label>
</li>
<li class="option">
    <input value="B" type="radio" class="radioOrCheck" name="answer{{ forloop.counter }}" id="0_answer_{{ forloop.counter }}_option_2"/>
    <label for="0_answer_{{ forloop.counter }}_option_2">
        B.<p class="ue" style="display: inline;">{{ que.que_B }}</p>
    </label>
</li>
<li class="option">
    <input value="C" type="radio" class="radioOrCheck" name="answer{{ forloop.counter }}" id="0_answer_{{ forloop.counter }}_option_3"/>
    <label for="0_answer_{{ forloop.counter }}_option_3">
        C.<p class="ue" style="display: inline;">{{ que.que_C }}</p>
    </label>
</li>
<li class="option">
    <input value="D" type="radio" class="radioOrCheck" name="answer{{ forloop.counter }}" id="0_answer_{{ forloop.counter }}_option_4"/>
    <label for="0_answer_{{ forloop.counter }}_option_4">
        D.<p class="ue" style="display: inline;">{{ que.que_D }}</p>
    </label>
</li>

templates/exam/module/showerrors.html
{% for question in questions %}
    {% if question.que_type == '1' %}
        <li>
        <div class="test_content_nr_tt">
            <i>{{ forloop.counter }}</i><span>(1分)</span><font>{{ question.que_content }}</font><b class="icon iconfont">&#xe881;</b>
        </div>
        <div class="test_content_nr_main">
            <ul>
                <li class="option">
                    <label>
                        A.<p class="ue" style="display: inline;">{{ question.que_A }}</p>
                    </label>
                </li>
                <li class="option">
                    <label>
                        B.<p class="ue" style="display: inline;">{{ question.que_B }}</p>
                    </label>
                </li>
                <li class="option">
                    <label>
                        C.<p class="ue" style="display: inline;">{{ question.que_C }}</p>
                    </label>
                </li>
                <li class="option">
                    <label>
                        D.<p class="ue" style="display: inline;">{{ question.que_D }}</p>
                    </label>
                </li>
            </ul>
        </div>
        <div class="test_content_nr_main">正确答案：<b>{{question.que_answer }}</b></div>
    </li>
    {% elif question.que_type == '2' %}
        <li>
        <div class="test_content_nr_tt">
            <i>{{ forloop.counter }}</i><span>(1分)</span><font>{{ question.que_content }}</font><b class="icon iconfont">&#xe881;</b>
        </div>
        <div class="test_content_nr_main">正确答案：<b>{{ question.switch_answer }}</b></div>
    </li>
    {% else %}
         <li>
        <div class="test_content_nr_tt">
            <i>{{ forloop.counter }}</i><font><pre style="font-family:'Courier New' ">{{question.que_content }}</pre></font><b class="icon iconfont">&#xe881;</b>
        </div>
        <div class="test_content_nr_main">
            <ul>
                <li class="option">
                </li>
            </ul>
        </div>
        <div class="test_content_nr_main">正确答案：<pre style="font-family:'Courier New';color: red">{{ question.que_answer }}</pre></div>
    </li>
    {% endif %}
{% endfor %}

templates/exam/module/showresult.html
{% if type == '选择题' %}
    {% for answer in  answers %}
        <li>
            <div class="test_content_nr_tt {% if answer.score == 0 %}err{% endif %}">
                <i>{{ forloop.counter }}</i><span>(1分)</span><font>{{ answer.que.que_content }}</font><b class="icon iconfont">&#xe881;</b>
            </div>
            <div class="test_content_nr_main">
                <ul>
                    <li class="option">
                        <label>
                            A.<p class="ue" style="display: inline;">{{ answer.que.que_A }}</p>
                        </label>
                    </li>
                    <li class="option">
                        <label>
                            B.<p class="ue" style="display: inline;">{{ answer.que.que_B }}</p>
                        </label>
                    </li>
                    <li class="option">
                        <label>
                            C.<p class="ue" style="display: inline;">{{ answer.que.que_C }}</p>
                        </label>
                    </li>
                    <li class="option">
                        <label>
                            D.<p class="ue" style="display: inline;">{{ answer.que.que_D }}</p>
                        </label>
                    </li>
                </ul>
            </div>
            <div class="test_content_nr_main">正确答案：<b>{{ answer.que.que_answer }}</b><br>你的答案：{{ answer.stu_answer }}</div>
        </li>
    {% endfor %}
{% elif type == '判断题' %}
    {% for answer in  answers %}
        <li>
            <div class="test_content_nr_tt {% if answer.score == 0 %}err{% endif %}">
                <i>{{ forloop.counter }}</i><span>(1分)</span><font>{{ answer.que.que_content }}</font><b class="icon iconfont">&#xe881;</b>
            </div>
            <div class="test_content_nr_main">正确答案：<b>{{ answer.que.switch_answer }}</b><br>你的答案：{{ answer.switch_answer }}</div>
        </li>
    {% endfor %}
{% else %}
    {% for answer in  answers %}
        <li>
            <div class="test_content_nr_tt">
                <i>{{ forloop.counter }}</i><span>(1分)</span><font><pre style="font-family:'Courier New' ">{{ answer.que.que_content }}</pre></font><b class="icon iconfont">&#xe881;</b>
            </div>
            <div class="test_content_nr_main">
                <ul>
                    <li class="option">
                        <textarea style="width: 100%;font-size: 18px;" rows="10">
                            {{ answer.stu_answer }}
                        </textarea>
                    </li>
                </ul>
            </div>
            <div class="test_content_nr_main">正确答案：<pre style="font-family:'Courier New';color: red">{{ answer.que.que_answer }}</pre></div>
        </li>
    {% endfor %}
{% endif %}